### ISSUE TITLE
Missing unit test for routine remove_items.SUBRIP_SUBTITLE_TESTS

### ISSUE THREAD

**Issue by mromina** [nmaguirre/eiffel-subtitle-converter#117]

**Comment by dromero19** [comment]
Solved in rev. 6f0c50f

**Comment by nricci** [comment]
The only positive test attempts to remove thing from an empty subtitle. This doesn't test much. Testing this feature appropriately is very important. Please, provide better, stronger tests.

**Comment by dromero19** [comment]
Fixed test in rev. 5b73740

**Comment by nricci** [comment]
Regarding the "test_remove_items_valid" test. The condition that you are testing (#items <= old #items) is already guaranteed by the postcondition. I think that, you want to assert something a bit stronger, like #items < old #items, because in this particular setting you have written the test so that the second item will be deleted. Or at least it should, if the remove_items worked correctly.

**Comment by dromero19** [comment]
Modification in tests. Solved in rev. 342dc26.
