### ISSUE TITLE
Missing implementation for subroutine Microdvd_subtitle.make_from_file

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/eiffel-subtitle-converter#155]

**Comment by ezedepetris** [comment]
Resolved in rev 992b7a9

**Comment by nicodomgz** [comment]
You should use "add_subtitle_item" rather than  "items.extend", (look at line 47 in  992b7a9 ). This is because you can make an invalid sequence. For Example, I can load from file the following sequence:

{1}{4}first_text
{3}{7}second_text
{2}{9}third_text

I use this sequence in my test (test_invalid_make_from_file_wrong_sequence).

**Comment by ezedepetris** [comment]
Resolved in rev 7a98fb9

**Comment by saiema** [comment]
After this [issue](https://github.com/nmaguirre/eiffel-subtitle-converter/issues/208) is resolved you should change the call from add_subtitle_item to the new feature in that issue.

**Comment by ezedepetris** [comment]
sory, but i dont understand you

**Comment by nicodomgz** [comment]
He says that when I'll implement add_constructed_subtitle_item, you should change "add_subtitle_item" to "add_constructed_subtitle_item".

**Comment by ezedepetris** [comment]
okey, resolved in rev d183953
