### ISSUE TITLE
Missing implementation for routine MICRODVD_SUBTITLE_ITEM.make_from_string

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/eiffel-subtitle-converter#157]

**Comment by ezedepetris** [comment]
Resolved in rev 6d743b9

**Comment by ezedepetris** [comment]
i recheck my solution and repair it in rev 74ea72a

**Comment by saiema** [comment]
There is no need to call **create i.default_create** because **i** is initialized with **0** as any non detachable Integer.

The condition **('}' /= line.item(i) and '{' /= line.item (i))** in the first **loop** should never be **false** since, if **line.item(i) = '}'** then the loop should have ended and the loop body couldn't be executed. If **line.item(i) = '{'** then the string representation is wrong (which you are assuming is not, because if you didn't assume that then you couldn't do **i := 2** in the loop initialization.

The second loop is not consistent with the first one, why you assume that you can start with **i := 2** in the first loop but don't assume that the second loop should start with **i := i + 2** ?. The condition inside the second loop also includes the condition in the loop's **until**.

You are not checking if the input string is a correct representation and the routine doesn't have a precondition that enforces that.

**Comment by ezedepetris** [comment]
Resolved in rev 80ca8e8, the precondition and postconditio aren't mine, so, i cant check that
