### ISSUE TITLE
Missing precondition for routine change_fps.MICRODVD_SUBTITLE

### ISSUE THREAD

**Issue by arangue** [nmaguirre/eiffel-subtitle-converter#28]

**Comment by arangue** [comment]
Resolved in rev. 59d3322

**Comment by nmaguirre** [comment]
FPS must be >12 (less than 12 is insufficient for a stream of frames to be perceived as a continous image).

**Comment by arangue** [comment]
Fixed in rev. 7be9b1239d28467c7849eafe2b96068dcdd66113

**Comment by nmaguirre** [comment]
Please do not use 12 directly, a constant should be used instead. A different user is doing so as we speak. I'm removing the 'resolved' tag, but wait to work on this issue until the 'min_valid_fps' constant is defined.

**Comment by nmaguirre** [comment]
Sorry, I made the comment in the wrong place. Please add 12 as a constant, instead of referring to the "magic" number. Define a feature:

min_valid_fps: INTEGER = 12

and add an appropriate comment to it. Then, in the precondition, use min_valid_fps instead of directly using 12. Thanks! Removing the 'resolved' tag, for the moment...

**Comment by arangue** [comment]
Fixed in rev. 73bf67fe704a02d6907543ca07e65f22cc03a214

**Comment by arangue** [comment]
Solved in rev. 8456377daeb15df15c39ed0e4379b72e434a01e7

**Comment by arangue** [comment]
Solved in rev. 8456377daeb15df15c39ed0e4379b72e434a01e7
