### ISSUE TITLE
Missing precondition for routine SUBRIP_SUBTITLE_TIME.rewind

### ISSUE THREAD

**Issue by nicoboccolini** [nmaguirre/eiffel-subtitle-converter#80]

**Comment by nicoboccolini** [comment]
solved in rev. 4ebd8a3cd2cf614102c34e14d5a8ea46adc43b17

**Comment by nricci** [comment]
The precondition needs to be stronger. In this case it would allow to execute the method in a scenario as the one in test "test_set_rewind_invalid_value". The result is that the method will break as expected, but due to a violation of the invariant on exit. From the design by contract standpoint this represents a bug in the supplier. To sum up, the precondition needs to, additionally, ask that the rewind amount is not so big that the result will be negative.

**Comment by nicoboccolini** [comment]
fixed in rev. 162d50b410b7d2fe0e05a8f3c3d8ca4a25422239

**Comment by nricci** [comment]
Great
